# Generated by Django 6.0.4 on 2026-04-23 12:28

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default='default', max_length=100)),
                ('base_rate_per_km', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('weight_rate_per_kg', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10)),
                ('fuel_surcharge_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
            ],
            options={
                'verbose_name': 'Pricing Config',
                'verbose_name_plural': 'Pricing Configs',
            },
        ),
    ]
